name: update_sitemap.yml

on:
  schedule:
    - cron: "30 17 * * *"  # Runs daily at 05 30 PM UTC
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual execution

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          cd marketing  # Navigate to the correct folder
          pip install -r requirements.txt  # Install dependencies

      - name: run_sitemap.py
        run: |
          cd marketing  # Ensure script runs inside the correct folder
          python run_sitemap.py  # Run the Python script

      - name: Commit and Push updated Sitemap files
        run: |
          cd marketing  # Ensure we're in the correct directory
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap/*.xml checkpoint.json  # Add new sitemap files and checkpoint
          git commit -m "Updated Sitemap" || echo "No changes to commit"
          git push
        continue-on-error: true  # Prevent failure if no changes occur
