name: Staging Validation

on:
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Check HTML Integrity
        run: |
          if grep -R "undefined" ./_site; then
            echo "Undefined variables found"
            exit 1
          fi

      - name: Validate Sitemap Exists
        run: |
          if [ ! -f "_site/sitemap.xml" ]; then
            echo "Missing sitemap"
            exit 1
          fi
