name: Update RSS Feed

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # Use the latest Python 3 version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies (if any)

      - name: Run RSS script
        run: python run_rss.py  # Execute the script

      - name: Commit and Push updated RSS feed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rss.xml  # Add the generated RSS feed file
          git commit -m "Updated RSS feed"
          git push
        continue-on-error: true  # Avoid breaking if no changes are detected
