name: Update Sitemap

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at midnight UTC
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # Use the latest Python 3 version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies (if any)

      - name: Run sitemap script
        run: python run_sitemap.py  # Execute the script

      - name: Commit and Push updated sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml  # Add the generated sitemap file
          git commit -m "Updated sitemap"
          git push
        continue-on-error: true  # Avoid breaking if no changes are detected
